// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lindell17/struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lindell17_2fstruct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lindell17_2fstruct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-suites/crypto-curve/proto_gen/curve_point.pb.switch.h"
#include "crypto-suites/crypto-paillier/proto_gen/paillier.pb.switch.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lindell17_2fstruct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lindell17_2fstruct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lindell17_2fstruct_2eproto;
namespace safeheron {
namespace proto {
namespace two_party_ecdsa {
namespace lindell17 {
class P1KeyShare;
struct P1KeyShareDefaultTypeInternal;
extern P1KeyShareDefaultTypeInternal _P1KeyShare_default_instance_;
class P2KeyShare;
struct P2KeyShareDefaultTypeInternal;
extern P2KeyShareDefaultTypeInternal _P2KeyShare_default_instance_;
}  // namespace lindell17
}  // namespace two_party_ecdsa
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::two_party_ecdsa::lindell17::P1KeyShare* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::P1KeyShare>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::P2KeyShare* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::P2KeyShare>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {
namespace two_party_ecdsa {
namespace lindell17 {

// ===================================================================

class P1KeyShare final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare) */ {
 public:
  inline P1KeyShare() : P1KeyShare(nullptr) {}
  ~P1KeyShare() override;
  explicit PROTOBUF_CONSTEXPR P1KeyShare(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P1KeyShare(const P1KeyShare& from);
  P1KeyShare(P1KeyShare&& from) noexcept
    : P1KeyShare() {
    *this = ::std::move(from);
  }

  inline P1KeyShare& operator=(const P1KeyShare& from) {
    CopyFrom(from);
    return *this;
  }
  inline P1KeyShare& operator=(P1KeyShare&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P1KeyShare& default_instance() {
    return *internal_default_instance();
  }
  static inline const P1KeyShare* internal_default_instance() {
    return reinterpret_cast<const P1KeyShare*>(
               &_P1KeyShare_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(P1KeyShare& a, P1KeyShare& b) {
    a.Swap(&b);
  }
  inline void Swap(P1KeyShare* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P1KeyShare* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  P1KeyShare* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<P1KeyShare>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const P1KeyShare& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const P1KeyShare& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P1KeyShare* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare";
  }
  protected:
  explicit P1KeyShare(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kX1FieldNumber = 1,
    kQFieldNumber = 2,
    kPailPrivFieldNumber = 3,
    kPailPubFieldNumber = 4,
  };
  // string x1 = 1;
  void clear_x1();
  const std::string& x1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_x1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_x1();
  PROTOBUF_NODISCARD std::string* release_x1();
  void set_allocated_x1(std::string* x1);
  private:
  const std::string& _internal_x1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_x1(const std::string& value);
  std::string* _internal_mutable_x1();
  public:

  // .safeheron.proto.CurvePoint Q = 2;
  bool has_q() const;
  private:
  bool _internal_has_q() const;
  public:
  void clear_q();
  const ::safeheron::proto::CurvePoint& q() const;
  PROTOBUF_NODISCARD ::safeheron::proto::CurvePoint* release_q();
  ::safeheron::proto::CurvePoint* mutable_q();
  void set_allocated_q(::safeheron::proto::CurvePoint* q);
  private:
  const ::safeheron::proto::CurvePoint& _internal_q() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_q();
  public:
  void unsafe_arena_set_allocated_q(
      ::safeheron::proto::CurvePoint* q);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_q();

  // .safeheron.proto.PailPriv pail_priv = 3;
  bool has_pail_priv() const;
  private:
  bool _internal_has_pail_priv() const;
  public:
  void clear_pail_priv();
  const ::safeheron::proto::PailPriv& pail_priv() const;
  PROTOBUF_NODISCARD ::safeheron::proto::PailPriv* release_pail_priv();
  ::safeheron::proto::PailPriv* mutable_pail_priv();
  void set_allocated_pail_priv(::safeheron::proto::PailPriv* pail_priv);
  private:
  const ::safeheron::proto::PailPriv& _internal_pail_priv() const;
  ::safeheron::proto::PailPriv* _internal_mutable_pail_priv();
  public:
  void unsafe_arena_set_allocated_pail_priv(
      ::safeheron::proto::PailPriv* pail_priv);
  ::safeheron::proto::PailPriv* unsafe_arena_release_pail_priv();

  // .safeheron.proto.PailPub pail_pub = 4;
  bool has_pail_pub() const;
  private:
  bool _internal_has_pail_pub() const;
  public:
  void clear_pail_pub();
  const ::safeheron::proto::PailPub& pail_pub() const;
  PROTOBUF_NODISCARD ::safeheron::proto::PailPub* release_pail_pub();
  ::safeheron::proto::PailPub* mutable_pail_pub();
  void set_allocated_pail_pub(::safeheron::proto::PailPub* pail_pub);
  private:
  const ::safeheron::proto::PailPub& _internal_pail_pub() const;
  ::safeheron::proto::PailPub* _internal_mutable_pail_pub();
  public:
  void unsafe_arena_set_allocated_pail_pub(
      ::safeheron::proto::PailPub* pail_pub);
  ::safeheron::proto::PailPub* unsafe_arena_release_pail_pub();

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr x1_;
  ::safeheron::proto::CurvePoint* q_;
  ::safeheron::proto::PailPriv* pail_priv_;
  ::safeheron::proto::PailPub* pail_pub_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fstruct_2eproto;
};
// -------------------------------------------------------------------

class P2KeyShare final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare) */ {
 public:
  inline P2KeyShare() : P2KeyShare(nullptr) {}
  ~P2KeyShare() override;
  explicit PROTOBUF_CONSTEXPR P2KeyShare(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2KeyShare(const P2KeyShare& from);
  P2KeyShare(P2KeyShare&& from) noexcept
    : P2KeyShare() {
    *this = ::std::move(from);
  }

  inline P2KeyShare& operator=(const P2KeyShare& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2KeyShare& operator=(P2KeyShare&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2KeyShare& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2KeyShare* internal_default_instance() {
    return reinterpret_cast<const P2KeyShare*>(
               &_P2KeyShare_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(P2KeyShare& a, P2KeyShare& b) {
    a.Swap(&b);
  }
  inline void Swap(P2KeyShare* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2KeyShare* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  P2KeyShare* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<P2KeyShare>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const P2KeyShare& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const P2KeyShare& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2KeyShare* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare";
  }
  protected:
  explicit P2KeyShare(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kX2FieldNumber = 1,
    kCFieldNumber = 4,
    kQFieldNumber = 2,
    kPailPubFieldNumber = 3,
  };
  // string x2 = 1;
  void clear_x2();
  const std::string& x2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_x2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_x2();
  PROTOBUF_NODISCARD std::string* release_x2();
  void set_allocated_x2(std::string* x2);
  private:
  const std::string& _internal_x2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_x2(const std::string& value);
  std::string* _internal_mutable_x2();
  public:

  // string c = 4;
  void clear_c();
  const std::string& c() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_c(ArgT0&& arg0, ArgT... args);
  std::string* mutable_c();
  PROTOBUF_NODISCARD std::string* release_c();
  void set_allocated_c(std::string* c);
  private:
  const std::string& _internal_c() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_c(const std::string& value);
  std::string* _internal_mutable_c();
  public:

  // .safeheron.proto.CurvePoint Q = 2;
  bool has_q() const;
  private:
  bool _internal_has_q() const;
  public:
  void clear_q();
  const ::safeheron::proto::CurvePoint& q() const;
  PROTOBUF_NODISCARD ::safeheron::proto::CurvePoint* release_q();
  ::safeheron::proto::CurvePoint* mutable_q();
  void set_allocated_q(::safeheron::proto::CurvePoint* q);
  private:
  const ::safeheron::proto::CurvePoint& _internal_q() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_q();
  public:
  void unsafe_arena_set_allocated_q(
      ::safeheron::proto::CurvePoint* q);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_q();

  // .safeheron.proto.PailPub pail_pub = 3;
  bool has_pail_pub() const;
  private:
  bool _internal_has_pail_pub() const;
  public:
  void clear_pail_pub();
  const ::safeheron::proto::PailPub& pail_pub() const;
  PROTOBUF_NODISCARD ::safeheron::proto::PailPub* release_pail_pub();
  ::safeheron::proto::PailPub* mutable_pail_pub();
  void set_allocated_pail_pub(::safeheron::proto::PailPub* pail_pub);
  private:
  const ::safeheron::proto::PailPub& _internal_pail_pub() const;
  ::safeheron::proto::PailPub* _internal_mutable_pail_pub();
  public:
  void unsafe_arena_set_allocated_pail_pub(
      ::safeheron::proto::PailPub* pail_pub);
  ::safeheron::proto::PailPub* unsafe_arena_release_pail_pub();

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr x2_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr c_;
  ::safeheron::proto::CurvePoint* q_;
  ::safeheron::proto::PailPub* pail_pub_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fstruct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// P1KeyShare

// string x1 = 1;
inline void P1KeyShare::clear_x1() {
  x1_.ClearToEmpty();
}
inline const std::string& P1KeyShare::x1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.x1)
  return _internal_x1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void P1KeyShare::set_x1(ArgT0&& arg0, ArgT... args) {
 
 x1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.x1)
}
inline std::string* P1KeyShare::mutable_x1() {
  std::string* _s = _internal_mutable_x1();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.x1)
  return _s;
}
inline const std::string& P1KeyShare::_internal_x1() const {
  return x1_.Get();
}
inline void P1KeyShare::_internal_set_x1(const std::string& value) {
  
  x1_.Set(value, GetArenaForAllocation());
}
inline std::string* P1KeyShare::_internal_mutable_x1() {
  
  return x1_.Mutable(GetArenaForAllocation());
}
inline std::string* P1KeyShare::release_x1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.x1)
  return x1_.Release();
}
inline void P1KeyShare::set_allocated_x1(std::string* x1) {
  if (x1 != nullptr) {
    
  } else {
    
  }
  x1_.SetAllocated(x1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (x1_.IsDefault()) {
    x1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.x1)
}

// .safeheron.proto.CurvePoint Q = 2;
inline bool P1KeyShare::_internal_has_q() const {
  return this != internal_default_instance() && q_ != nullptr;
}
inline bool P1KeyShare::has_q() const {
  return _internal_has_q();
}
inline const ::safeheron::proto::CurvePoint& P1KeyShare::_internal_q() const {
  const ::safeheron::proto::CurvePoint* p = q_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& P1KeyShare::q() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.Q)
  return _internal_q();
}
inline void P1KeyShare::unsafe_arena_set_allocated_q(
    ::safeheron::proto::CurvePoint* q) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(q_);
  }
  q_ = q;
  if (q) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.Q)
}
inline ::safeheron::proto::CurvePoint* P1KeyShare::release_q() {
  
  ::safeheron::proto::CurvePoint* temp = q_;
  q_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::CurvePoint* P1KeyShare::unsafe_arena_release_q() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.Q)
  
  ::safeheron::proto::CurvePoint* temp = q_;
  q_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* P1KeyShare::_internal_mutable_q() {
  
  if (q_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaForAllocation());
    q_ = p;
  }
  return q_;
}
inline ::safeheron::proto::CurvePoint* P1KeyShare::mutable_q() {
  ::safeheron::proto::CurvePoint* _msg = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.Q)
  return _msg;
}
inline void P1KeyShare::set_allocated_q(::safeheron::proto::CurvePoint* q) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(q_);
  }
  if (q) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(q));
    if (message_arena != submessage_arena) {
      q = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, q, submessage_arena);
    }
    
  } else {
    
  }
  q_ = q;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.Q)
}

// .safeheron.proto.PailPriv pail_priv = 3;
inline bool P1KeyShare::_internal_has_pail_priv() const {
  return this != internal_default_instance() && pail_priv_ != nullptr;
}
inline bool P1KeyShare::has_pail_priv() const {
  return _internal_has_pail_priv();
}
inline const ::safeheron::proto::PailPriv& P1KeyShare::_internal_pail_priv() const {
  const ::safeheron::proto::PailPriv* p = pail_priv_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::PailPriv&>(
      ::safeheron::proto::_PailPriv_default_instance_);
}
inline const ::safeheron::proto::PailPriv& P1KeyShare::pail_priv() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_priv)
  return _internal_pail_priv();
}
inline void P1KeyShare::unsafe_arena_set_allocated_pail_priv(
    ::safeheron::proto::PailPriv* pail_priv) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_priv_);
  }
  pail_priv_ = pail_priv;
  if (pail_priv) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_priv)
}
inline ::safeheron::proto::PailPriv* P1KeyShare::release_pail_priv() {
  
  ::safeheron::proto::PailPriv* temp = pail_priv_;
  pail_priv_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::PailPriv* P1KeyShare::unsafe_arena_release_pail_priv() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_priv)
  
  ::safeheron::proto::PailPriv* temp = pail_priv_;
  pail_priv_ = nullptr;
  return temp;
}
inline ::safeheron::proto::PailPriv* P1KeyShare::_internal_mutable_pail_priv() {
  
  if (pail_priv_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::PailPriv>(GetArenaForAllocation());
    pail_priv_ = p;
  }
  return pail_priv_;
}
inline ::safeheron::proto::PailPriv* P1KeyShare::mutable_pail_priv() {
  ::safeheron::proto::PailPriv* _msg = _internal_mutable_pail_priv();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_priv)
  return _msg;
}
inline void P1KeyShare::set_allocated_pail_priv(::safeheron::proto::PailPriv* pail_priv) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_priv_);
  }
  if (pail_priv) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_priv));
    if (message_arena != submessage_arena) {
      pail_priv = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pail_priv, submessage_arena);
    }
    
  } else {
    
  }
  pail_priv_ = pail_priv;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_priv)
}

// .safeheron.proto.PailPub pail_pub = 4;
inline bool P1KeyShare::_internal_has_pail_pub() const {
  return this != internal_default_instance() && pail_pub_ != nullptr;
}
inline bool P1KeyShare::has_pail_pub() const {
  return _internal_has_pail_pub();
}
inline const ::safeheron::proto::PailPub& P1KeyShare::_internal_pail_pub() const {
  const ::safeheron::proto::PailPub* p = pail_pub_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::PailPub&>(
      ::safeheron::proto::_PailPub_default_instance_);
}
inline const ::safeheron::proto::PailPub& P1KeyShare::pail_pub() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_pub)
  return _internal_pail_pub();
}
inline void P1KeyShare::unsafe_arena_set_allocated_pail_pub(
    ::safeheron::proto::PailPub* pail_pub) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub_);
  }
  pail_pub_ = pail_pub;
  if (pail_pub) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_pub)
}
inline ::safeheron::proto::PailPub* P1KeyShare::release_pail_pub() {
  
  ::safeheron::proto::PailPub* temp = pail_pub_;
  pail_pub_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::PailPub* P1KeyShare::unsafe_arena_release_pail_pub() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_pub)
  
  ::safeheron::proto::PailPub* temp = pail_pub_;
  pail_pub_ = nullptr;
  return temp;
}
inline ::safeheron::proto::PailPub* P1KeyShare::_internal_mutable_pail_pub() {
  
  if (pail_pub_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::PailPub>(GetArenaForAllocation());
    pail_pub_ = p;
  }
  return pail_pub_;
}
inline ::safeheron::proto::PailPub* P1KeyShare::mutable_pail_pub() {
  ::safeheron::proto::PailPub* _msg = _internal_mutable_pail_pub();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_pub)
  return _msg;
}
inline void P1KeyShare::set_allocated_pail_pub(::safeheron::proto::PailPub* pail_pub) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub_);
  }
  if (pail_pub) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub));
    if (message_arena != submessage_arena) {
      pail_pub = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pail_pub, submessage_arena);
    }
    
  } else {
    
  }
  pail_pub_ = pail_pub;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P1KeyShare.pail_pub)
}

// -------------------------------------------------------------------

// P2KeyShare

// string x2 = 1;
inline void P2KeyShare::clear_x2() {
  x2_.ClearToEmpty();
}
inline const std::string& P2KeyShare::x2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.x2)
  return _internal_x2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void P2KeyShare::set_x2(ArgT0&& arg0, ArgT... args) {
 
 x2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.x2)
}
inline std::string* P2KeyShare::mutable_x2() {
  std::string* _s = _internal_mutable_x2();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.x2)
  return _s;
}
inline const std::string& P2KeyShare::_internal_x2() const {
  return x2_.Get();
}
inline void P2KeyShare::_internal_set_x2(const std::string& value) {
  
  x2_.Set(value, GetArenaForAllocation());
}
inline std::string* P2KeyShare::_internal_mutable_x2() {
  
  return x2_.Mutable(GetArenaForAllocation());
}
inline std::string* P2KeyShare::release_x2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.x2)
  return x2_.Release();
}
inline void P2KeyShare::set_allocated_x2(std::string* x2) {
  if (x2 != nullptr) {
    
  } else {
    
  }
  x2_.SetAllocated(x2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (x2_.IsDefault()) {
    x2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.x2)
}

// .safeheron.proto.CurvePoint Q = 2;
inline bool P2KeyShare::_internal_has_q() const {
  return this != internal_default_instance() && q_ != nullptr;
}
inline bool P2KeyShare::has_q() const {
  return _internal_has_q();
}
inline const ::safeheron::proto::CurvePoint& P2KeyShare::_internal_q() const {
  const ::safeheron::proto::CurvePoint* p = q_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& P2KeyShare::q() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.Q)
  return _internal_q();
}
inline void P2KeyShare::unsafe_arena_set_allocated_q(
    ::safeheron::proto::CurvePoint* q) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(q_);
  }
  q_ = q;
  if (q) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.Q)
}
inline ::safeheron::proto::CurvePoint* P2KeyShare::release_q() {
  
  ::safeheron::proto::CurvePoint* temp = q_;
  q_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::CurvePoint* P2KeyShare::unsafe_arena_release_q() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.Q)
  
  ::safeheron::proto::CurvePoint* temp = q_;
  q_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* P2KeyShare::_internal_mutable_q() {
  
  if (q_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaForAllocation());
    q_ = p;
  }
  return q_;
}
inline ::safeheron::proto::CurvePoint* P2KeyShare::mutable_q() {
  ::safeheron::proto::CurvePoint* _msg = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.Q)
  return _msg;
}
inline void P2KeyShare::set_allocated_q(::safeheron::proto::CurvePoint* q) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(q_);
  }
  if (q) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(q));
    if (message_arena != submessage_arena) {
      q = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, q, submessage_arena);
    }
    
  } else {
    
  }
  q_ = q;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.Q)
}

// .safeheron.proto.PailPub pail_pub = 3;
inline bool P2KeyShare::_internal_has_pail_pub() const {
  return this != internal_default_instance() && pail_pub_ != nullptr;
}
inline bool P2KeyShare::has_pail_pub() const {
  return _internal_has_pail_pub();
}
inline const ::safeheron::proto::PailPub& P2KeyShare::_internal_pail_pub() const {
  const ::safeheron::proto::PailPub* p = pail_pub_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::PailPub&>(
      ::safeheron::proto::_PailPub_default_instance_);
}
inline const ::safeheron::proto::PailPub& P2KeyShare::pail_pub() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.pail_pub)
  return _internal_pail_pub();
}
inline void P2KeyShare::unsafe_arena_set_allocated_pail_pub(
    ::safeheron::proto::PailPub* pail_pub) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub_);
  }
  pail_pub_ = pail_pub;
  if (pail_pub) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.pail_pub)
}
inline ::safeheron::proto::PailPub* P2KeyShare::release_pail_pub() {
  
  ::safeheron::proto::PailPub* temp = pail_pub_;
  pail_pub_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::PailPub* P2KeyShare::unsafe_arena_release_pail_pub() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.pail_pub)
  
  ::safeheron::proto::PailPub* temp = pail_pub_;
  pail_pub_ = nullptr;
  return temp;
}
inline ::safeheron::proto::PailPub* P2KeyShare::_internal_mutable_pail_pub() {
  
  if (pail_pub_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::PailPub>(GetArenaForAllocation());
    pail_pub_ = p;
  }
  return pail_pub_;
}
inline ::safeheron::proto::PailPub* P2KeyShare::mutable_pail_pub() {
  ::safeheron::proto::PailPub* _msg = _internal_mutable_pail_pub();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.pail_pub)
  return _msg;
}
inline void P2KeyShare::set_allocated_pail_pub(::safeheron::proto::PailPub* pail_pub) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub_);
  }
  if (pail_pub) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pail_pub));
    if (message_arena != submessage_arena) {
      pail_pub = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pail_pub, submessage_arena);
    }
    
  } else {
    
  }
  pail_pub_ = pail_pub;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.pail_pub)
}

// string c = 4;
inline void P2KeyShare::clear_c() {
  c_.ClearToEmpty();
}
inline const std::string& P2KeyShare::c() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.c)
  return _internal_c();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void P2KeyShare::set_c(ArgT0&& arg0, ArgT... args) {
 
 c_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.c)
}
inline std::string* P2KeyShare::mutable_c() {
  std::string* _s = _internal_mutable_c();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.c)
  return _s;
}
inline const std::string& P2KeyShare::_internal_c() const {
  return c_.Get();
}
inline void P2KeyShare::_internal_set_c(const std::string& value) {
  
  c_.Set(value, GetArenaForAllocation());
}
inline std::string* P2KeyShare::_internal_mutable_c() {
  
  return c_.Mutable(GetArenaForAllocation());
}
inline std::string* P2KeyShare::release_c() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.c)
  return c_.Release();
}
inline void P2KeyShare::set_allocated_c(std::string* c) {
  if (c != nullptr) {
    
  } else {
    
  }
  c_.SetAllocated(c, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (c_.IsDefault()) {
    c_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.P2KeyShare.c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lindell17
}  // namespace two_party_ecdsa
}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lindell17_2fstruct_2eproto
