// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmp/aux_info_key_refresh.proto

#include "aux_info_key_refresh.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_curve_5fpoint_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CurvePoint_curve_5fpoint_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_zkp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DLogProof_V2_zkp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_zkp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NoSmallFactorProof_zkp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_zkp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PailBlumModulusProof_zkp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_zkp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TwoDLNProof_zkp_2eproto;
namespace safeheron {
namespace proto {
namespace multi_party_ecdsa {
namespace cmp {
namespace aux_info_key_refresh {
class Round0BCMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Round0BCMessage> _instance;
} _Round0BCMessage_default_instance_;
class Round1BCMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Round1BCMessage> _instance;
} _Round1BCMessage_default_instance_;
class Round2P2PMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Round2P2PMessage> _instance;
} _Round2P2PMessage_default_instance_;
}  // namespace aux_info_key_refresh
}  // namespace cmp
}  // namespace multi_party_ecdsa
}  // namespace proto
}  // namespace safeheron
static void InitDefaultsscc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round0BCMessage_default_instance_;
    new (ptr) ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto}, {}};

static void InitDefaultsscc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round1BCMessage_default_instance_;
    new (ptr) ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto}, {
      &scc_info_CurvePoint_curve_5fpoint_2eproto.base,
      &scc_info_TwoDLNProof_zkp_2eproto.base,}};

static void InitDefaultsscc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round2P2PMessage_default_instance_;
    new (ptr) ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto}, {
      &scc_info_PailBlumModulusProof_zkp_2eproto.base,
      &scc_info_NoSmallFactorProof_zkp_2eproto.base,
      &scc_info_DLogProof_V2_zkp_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cmp_2faux_5finfo_5fkey_5frefresh_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cmp_2faux_5finfo_5fkey_5frefresh_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cmp_2faux_5finfo_5fkey_5frefresh_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cmp_2faux_5finfo_5fkey_5frefresh_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage, ssid_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage, index_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage, v_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, ssid_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, index_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, party_id_arr_1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, g_x_arr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, c_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, party_id_arr_2_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, a_arr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, g_y_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, b_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, s_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, t_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, psi_tilde_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, rho_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage, u_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, ssid_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, index_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, psi_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, phi_ij_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, pi_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, c_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage, psi_ij_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage)},
  { 8, -1, sizeof(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage)},
  { 28, -1, sizeof(::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round0BCMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round1BCMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::_Round2P2PMessage_default_instance_),
};

const char descriptor_table_protodef_cmp_2faux_5finfo_5fkey_5frefresh_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036cmp/aux_info_key_refresh.proto\022:safehe"
  "ron.proto.multi_party_ecdsa.cmp.aux_info"
  "_key_refresh\032\021curve_point.proto\032\tzkp.pro"
  "to\"9\n\017Round0BCMessage\022\014\n\004ssid\030\001 \001(\t\022\r\n\005i"
  "ndex\030\002 \001(\t\022\t\n\001V\030\003 \001(\t\"\234\003\n\017Round1BCMessag"
  "e\022\014\n\004ssid\030\001 \001(\t\022\r\n\005index\030\002 \001(\t\022\026\n\016party_"
  "id_arr_1\030\003 \003(\t\022,\n\007g_x_arr\030\004 \003(\0132\033.safehe"
  "ron.proto.CurvePoint\022&\n\001c\030\005 \003(\0132\033.safehe"
  "ron.proto.CurvePoint\022\026\n\016party_id_arr_2\030\006"
  " \003(\t\022*\n\005A_arr\030\007 \003(\0132\033.safeheron.proto.Cu"
  "rvePoint\022(\n\003g_y\030\010 \001(\0132\033.safeheron.proto."
  "CurvePoint\022&\n\001B\030\t \001(\0132\033.safeheron.proto."
  "CurvePoint\022\t\n\001N\030\n \001(\t\022\t\n\001s\030\013 \001(\t\022\t\n\001t\030\014 "
  "\001(\t\022/\n\tpsi_tilde\030\r \001(\0132\034.safeheron.proto"
  ".TwoDLNProof\022\013\n\003rho\030\016 \001(\t\022\t\n\001u\030\017 \001(\t\"\375\001\n"
  "\020Round2P2PMessage\022\014\n\004ssid\030\001 \001(\t\022\r\n\005index"
  "\030\002 \001(\t\0222\n\003psi\030\003 \001(\0132%.safeheron.proto.Pa"
  "ilBlumModulusProof\0223\n\006phi_ij\030\004 \001(\0132#.saf"
  "eheron.proto.NoSmallFactorProof\022)\n\002pi\030\005 "
  "\001(\0132\035.safeheron.proto.DLogProof_V2\022\t\n\001C\030"
  "\006 \001(\t\022-\n\006psi_ij\030\007 \001(\0132\035.safeheron.proto."
  "DLogProof_V2b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_deps[2] = {
  &::descriptor_table_curve_5fpoint_2eproto,
  &::descriptor_table_zkp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_sccs[3] = {
  &scc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base,
  &scc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base,
  &scc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto = {
  false, false, descriptor_table_protodef_cmp_2faux_5finfo_5fkey_5frefresh_2eproto, "cmp/aux_info_key_refresh.proto", 860,
  &descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_once, descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_sccs, descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto_deps, 3, 2,
  schemas, file_default_instances, TableStruct_cmp_2faux_5finfo_5fkey_5frefresh_2eproto::offsets,
  file_level_metadata_cmp_2faux_5finfo_5fkey_5frefresh_2eproto, 3, file_level_enum_descriptors_cmp_2faux_5finfo_5fkey_5frefresh_2eproto, file_level_service_descriptors_cmp_2faux_5finfo_5fkey_5frefresh_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cmp_2faux_5finfo_5fkey_5frefresh_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_cmp_2faux_5finfo_5fkey_5frefresh_2eproto)), true);
namespace safeheron {
namespace proto {
namespace multi_party_ecdsa {
namespace cmp {
namespace aux_info_key_refresh {

// ===================================================================

class Round0BCMessage::_Internal {
 public:
};

Round0BCMessage::Round0BCMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
}
Round0BCMessage::Round0BCMessage(const Round0BCMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ssid().empty()) {
    ssid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ssid(), 
      GetArena());
  }
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_index().empty()) {
    index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_index(), 
      GetArena());
  }
  v_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_v().empty()) {
    v_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_v(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
}

void Round0BCMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  v_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Round0BCMessage::~Round0BCMessage() {
  // @@protoc_insertion_point(destructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Round0BCMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ssid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  v_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Round0BCMessage::ArenaDtor(void* object) {
  Round0BCMessage* _this = reinterpret_cast< Round0BCMessage* >(object);
  (void)_this;
}
void Round0BCMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Round0BCMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Round0BCMessage& Round0BCMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Round0BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  return *internal_default_instance();
}


void Round0BCMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ssid_.ClearToEmpty();
  index_.ClearToEmpty();
  v_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Round0BCMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string ssid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ssid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.ssid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_index();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.index"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string V = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_v();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.V"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Round0BCMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ssid().data(), static_cast<int>(this->_internal_ssid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.ssid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ssid(), target);
  }

  // string index = 2;
  if (this->index().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_index().data(), static_cast<int>(this->_internal_index().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.index");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_index(), target);
  }

  // string V = 3;
  if (this->v().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_v().data(), static_cast<int>(this->_internal_v().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage.V");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_v(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  return target;
}

size_t Round0BCMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());
  }

  // string index = 2;
  if (this->index().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_index());
  }

  // string V = 3;
  if (this->v().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_v());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Round0BCMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const Round0BCMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Round0BCMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
    MergeFrom(*source);
  }
}

void Round0BCMessage::MergeFrom(const Round0BCMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ssid().size() > 0) {
    _internal_set_ssid(from._internal_ssid());
  }
  if (from.index().size() > 0) {
    _internal_set_index(from._internal_index());
  }
  if (from.v().size() > 0) {
    _internal_set_v(from._internal_v());
  }
}

void Round0BCMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Round0BCMessage::CopyFrom(const Round0BCMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round0BCMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Round0BCMessage::IsInitialized() const {
  return true;
}

void Round0BCMessage::InternalSwap(Round0BCMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ssid_.Swap(&other->ssid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  index_.Swap(&other->index_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  v_.Swap(&other->v_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata Round0BCMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class Round1BCMessage::_Internal {
 public:
  static const ::safeheron::proto::CurvePoint& g_y(const Round1BCMessage* msg);
  static const ::safeheron::proto::CurvePoint& b(const Round1BCMessage* msg);
  static const ::safeheron::proto::TwoDLNProof& psi_tilde(const Round1BCMessage* msg);
};

const ::safeheron::proto::CurvePoint&
Round1BCMessage::_Internal::g_y(const Round1BCMessage* msg) {
  return *msg->g_y_;
}
const ::safeheron::proto::CurvePoint&
Round1BCMessage::_Internal::b(const Round1BCMessage* msg) {
  return *msg->b_;
}
const ::safeheron::proto::TwoDLNProof&
Round1BCMessage::_Internal::psi_tilde(const Round1BCMessage* msg) {
  return *msg->psi_tilde_;
}
void Round1BCMessage::clear_g_x_arr() {
  g_x_arr_.Clear();
}
void Round1BCMessage::clear_c() {
  c_.Clear();
}
void Round1BCMessage::clear_a_arr() {
  a_arr_.Clear();
}
void Round1BCMessage::clear_g_y() {
  if (GetArena() == nullptr && g_y_ != nullptr) {
    delete g_y_;
  }
  g_y_ = nullptr;
}
void Round1BCMessage::clear_b() {
  if (GetArena() == nullptr && b_ != nullptr) {
    delete b_;
  }
  b_ = nullptr;
}
void Round1BCMessage::clear_psi_tilde() {
  if (GetArena() == nullptr && psi_tilde_ != nullptr) {
    delete psi_tilde_;
  }
  psi_tilde_ = nullptr;
}
Round1BCMessage::Round1BCMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  party_id_arr_1_(arena),
  g_x_arr_(arena),
  c_(arena),
  party_id_arr_2_(arena),
  a_arr_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
}
Round1BCMessage::Round1BCMessage(const Round1BCMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      party_id_arr_1_(from.party_id_arr_1_),
      g_x_arr_(from.g_x_arr_),
      c_(from.c_),
      party_id_arr_2_(from.party_id_arr_2_),
      a_arr_(from.a_arr_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ssid().empty()) {
    ssid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ssid(), 
      GetArena());
  }
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_index().empty()) {
    index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_index(), 
      GetArena());
  }
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_n().empty()) {
    n_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_n(), 
      GetArena());
  }
  s_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_s().empty()) {
    s_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_s(), 
      GetArena());
  }
  t_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_t().empty()) {
    t_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_t(), 
      GetArena());
  }
  rho_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_rho().empty()) {
    rho_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_rho(), 
      GetArena());
  }
  u_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_u().empty()) {
    u_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_u(), 
      GetArena());
  }
  if (from._internal_has_g_y()) {
    g_y_ = new ::safeheron::proto::CurvePoint(*from.g_y_);
  } else {
    g_y_ = nullptr;
  }
  if (from._internal_has_b()) {
    b_ = new ::safeheron::proto::CurvePoint(*from.b_);
  } else {
    b_ = nullptr;
  }
  if (from._internal_has_psi_tilde()) {
    psi_tilde_ = new ::safeheron::proto::TwoDLNProof(*from.psi_tilde_);
  } else {
    psi_tilde_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
}

void Round1BCMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  s_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  t_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rho_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  u_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&g_y_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&psi_tilde_) -
      reinterpret_cast<char*>(&g_y_)) + sizeof(psi_tilde_));
}

Round1BCMessage::~Round1BCMessage() {
  // @@protoc_insertion_point(destructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Round1BCMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ssid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  n_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  s_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  t_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rho_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  u_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete g_y_;
  if (this != internal_default_instance()) delete b_;
  if (this != internal_default_instance()) delete psi_tilde_;
}

void Round1BCMessage::ArenaDtor(void* object) {
  Round1BCMessage* _this = reinterpret_cast< Round1BCMessage* >(object);
  (void)_this;
}
void Round1BCMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Round1BCMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Round1BCMessage& Round1BCMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Round1BCMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  return *internal_default_instance();
}


void Round1BCMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  party_id_arr_1_.Clear();
  g_x_arr_.Clear();
  c_.Clear();
  party_id_arr_2_.Clear();
  a_arr_.Clear();
  ssid_.ClearToEmpty();
  index_.ClearToEmpty();
  n_.ClearToEmpty();
  s_.ClearToEmpty();
  t_.ClearToEmpty();
  rho_.ClearToEmpty();
  u_.ClearToEmpty();
  if (GetArena() == nullptr && g_y_ != nullptr) {
    delete g_y_;
  }
  g_y_ = nullptr;
  if (GetArena() == nullptr && b_ != nullptr) {
    delete b_;
  }
  b_ = nullptr;
  if (GetArena() == nullptr && psi_tilde_ != nullptr) {
    delete psi_tilde_;
  }
  psi_tilde_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Round1BCMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string ssid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ssid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.ssid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_index();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.index"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string party_id_arr_1 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_party_id_arr_1();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.party_id_arr_1"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .safeheron.proto.CurvePoint g_x_arr = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_g_x_arr(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .safeheron.proto.CurvePoint c = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_c(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated string party_id_arr_2 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_party_id_arr_2();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.party_id_arr_2"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .safeheron.proto.CurvePoint A_arr = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_a_arr(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.CurvePoint g_y = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_g_y(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.CurvePoint B = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_b(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string N = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_n();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.N"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string s = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          auto str = _internal_mutable_s();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.s"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string t = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          auto str = _internal_mutable_t();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.t"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.TwoDLNProof psi_tilde = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_psi_tilde(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string rho = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          auto str = _internal_mutable_rho();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.rho"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string u = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          auto str = _internal_mutable_u();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.u"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Round1BCMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ssid().data(), static_cast<int>(this->_internal_ssid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.ssid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ssid(), target);
  }

  // string index = 2;
  if (this->index().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_index().data(), static_cast<int>(this->_internal_index().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.index");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_index(), target);
  }

  // repeated string party_id_arr_1 = 3;
  for (int i = 0, n = this->_internal_party_id_arr_1_size(); i < n; i++) {
    const auto& s = this->_internal_party_id_arr_1(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.party_id_arr_1");
    target = stream->WriteString(3, s, target);
  }

  // repeated .safeheron.proto.CurvePoint g_x_arr = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_g_x_arr_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_g_x_arr(i), target, stream);
  }

  // repeated .safeheron.proto.CurvePoint c = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_c_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_c(i), target, stream);
  }

  // repeated string party_id_arr_2 = 6;
  for (int i = 0, n = this->_internal_party_id_arr_2_size(); i < n; i++) {
    const auto& s = this->_internal_party_id_arr_2(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.party_id_arr_2");
    target = stream->WriteString(6, s, target);
  }

  // repeated .safeheron.proto.CurvePoint A_arr = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_a_arr_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_a_arr(i), target, stream);
  }

  // .safeheron.proto.CurvePoint g_y = 8;
  if (this->has_g_y()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::g_y(this), target, stream);
  }

  // .safeheron.proto.CurvePoint B = 9;
  if (this->has_b()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::b(this), target, stream);
  }

  // string N = 10;
  if (this->n().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_n().data(), static_cast<int>(this->_internal_n().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.N");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_n(), target);
  }

  // string s = 11;
  if (this->s().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_s().data(), static_cast<int>(this->_internal_s().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.s");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_s(), target);
  }

  // string t = 12;
  if (this->t().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_t().data(), static_cast<int>(this->_internal_t().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.t");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_t(), target);
  }

  // .safeheron.proto.TwoDLNProof psi_tilde = 13;
  if (this->has_psi_tilde()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        13, _Internal::psi_tilde(this), target, stream);
  }

  // string rho = 14;
  if (this->rho().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rho().data(), static_cast<int>(this->_internal_rho().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.rho");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_rho(), target);
  }

  // string u = 15;
  if (this->u().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_u().data(), static_cast<int>(this->_internal_u().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage.u");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_u(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  return target;
}

size_t Round1BCMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string party_id_arr_1 = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(party_id_arr_1_.size());
  for (int i = 0, n = party_id_arr_1_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      party_id_arr_1_.Get(i));
  }

  // repeated .safeheron.proto.CurvePoint g_x_arr = 4;
  total_size += 1UL * this->_internal_g_x_arr_size();
  for (const auto& msg : this->g_x_arr_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .safeheron.proto.CurvePoint c = 5;
  total_size += 1UL * this->_internal_c_size();
  for (const auto& msg : this->c_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated string party_id_arr_2 = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(party_id_arr_2_.size());
  for (int i = 0, n = party_id_arr_2_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      party_id_arr_2_.Get(i));
  }

  // repeated .safeheron.proto.CurvePoint A_arr = 7;
  total_size += 1UL * this->_internal_a_arr_size();
  for (const auto& msg : this->a_arr_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());
  }

  // string index = 2;
  if (this->index().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_index());
  }

  // string N = 10;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_n());
  }

  // string s = 11;
  if (this->s().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_s());
  }

  // string t = 12;
  if (this->t().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_t());
  }

  // string rho = 14;
  if (this->rho().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rho());
  }

  // string u = 15;
  if (this->u().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_u());
  }

  // .safeheron.proto.CurvePoint g_y = 8;
  if (this->has_g_y()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *g_y_);
  }

  // .safeheron.proto.CurvePoint B = 9;
  if (this->has_b()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *b_);
  }

  // .safeheron.proto.TwoDLNProof psi_tilde = 13;
  if (this->has_psi_tilde()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *psi_tilde_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Round1BCMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const Round1BCMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Round1BCMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
    MergeFrom(*source);
  }
}

void Round1BCMessage::MergeFrom(const Round1BCMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  party_id_arr_1_.MergeFrom(from.party_id_arr_1_);
  g_x_arr_.MergeFrom(from.g_x_arr_);
  c_.MergeFrom(from.c_);
  party_id_arr_2_.MergeFrom(from.party_id_arr_2_);
  a_arr_.MergeFrom(from.a_arr_);
  if (from.ssid().size() > 0) {
    _internal_set_ssid(from._internal_ssid());
  }
  if (from.index().size() > 0) {
    _internal_set_index(from._internal_index());
  }
  if (from.n().size() > 0) {
    _internal_set_n(from._internal_n());
  }
  if (from.s().size() > 0) {
    _internal_set_s(from._internal_s());
  }
  if (from.t().size() > 0) {
    _internal_set_t(from._internal_t());
  }
  if (from.rho().size() > 0) {
    _internal_set_rho(from._internal_rho());
  }
  if (from.u().size() > 0) {
    _internal_set_u(from._internal_u());
  }
  if (from.has_g_y()) {
    _internal_mutable_g_y()->::safeheron::proto::CurvePoint::MergeFrom(from._internal_g_y());
  }
  if (from.has_b()) {
    _internal_mutable_b()->::safeheron::proto::CurvePoint::MergeFrom(from._internal_b());
  }
  if (from.has_psi_tilde()) {
    _internal_mutable_psi_tilde()->::safeheron::proto::TwoDLNProof::MergeFrom(from._internal_psi_tilde());
  }
}

void Round1BCMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Round1BCMessage::CopyFrom(const Round1BCMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round1BCMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Round1BCMessage::IsInitialized() const {
  return true;
}

void Round1BCMessage::InternalSwap(Round1BCMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  party_id_arr_1_.InternalSwap(&other->party_id_arr_1_);
  g_x_arr_.InternalSwap(&other->g_x_arr_);
  c_.InternalSwap(&other->c_);
  party_id_arr_2_.InternalSwap(&other->party_id_arr_2_);
  a_arr_.InternalSwap(&other->a_arr_);
  ssid_.Swap(&other->ssid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  index_.Swap(&other->index_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  n_.Swap(&other->n_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  s_.Swap(&other->s_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  t_.Swap(&other->t_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rho_.Swap(&other->rho_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  u_.Swap(&other->u_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Round1BCMessage, psi_tilde_)
      + sizeof(Round1BCMessage::psi_tilde_)
      - PROTOBUF_FIELD_OFFSET(Round1BCMessage, g_y_)>(
          reinterpret_cast<char*>(&g_y_),
          reinterpret_cast<char*>(&other->g_y_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Round1BCMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class Round2P2PMessage::_Internal {
 public:
  static const ::safeheron::proto::PailBlumModulusProof& psi(const Round2P2PMessage* msg);
  static const ::safeheron::proto::NoSmallFactorProof& phi_ij(const Round2P2PMessage* msg);
  static const ::safeheron::proto::DLogProof_V2& pi(const Round2P2PMessage* msg);
  static const ::safeheron::proto::DLogProof_V2& psi_ij(const Round2P2PMessage* msg);
};

const ::safeheron::proto::PailBlumModulusProof&
Round2P2PMessage::_Internal::psi(const Round2P2PMessage* msg) {
  return *msg->psi_;
}
const ::safeheron::proto::NoSmallFactorProof&
Round2P2PMessage::_Internal::phi_ij(const Round2P2PMessage* msg) {
  return *msg->phi_ij_;
}
const ::safeheron::proto::DLogProof_V2&
Round2P2PMessage::_Internal::pi(const Round2P2PMessage* msg) {
  return *msg->pi_;
}
const ::safeheron::proto::DLogProof_V2&
Round2P2PMessage::_Internal::psi_ij(const Round2P2PMessage* msg) {
  return *msg->psi_ij_;
}
void Round2P2PMessage::clear_psi() {
  if (GetArena() == nullptr && psi_ != nullptr) {
    delete psi_;
  }
  psi_ = nullptr;
}
void Round2P2PMessage::clear_phi_ij() {
  if (GetArena() == nullptr && phi_ij_ != nullptr) {
    delete phi_ij_;
  }
  phi_ij_ = nullptr;
}
void Round2P2PMessage::clear_pi() {
  if (GetArena() == nullptr && pi_ != nullptr) {
    delete pi_;
  }
  pi_ = nullptr;
}
void Round2P2PMessage::clear_psi_ij() {
  if (GetArena() == nullptr && psi_ij_ != nullptr) {
    delete psi_ij_;
  }
  psi_ij_ = nullptr;
}
Round2P2PMessage::Round2P2PMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
}
Round2P2PMessage::Round2P2PMessage(const Round2P2PMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ssid().empty()) {
    ssid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ssid(), 
      GetArena());
  }
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_index().empty()) {
    index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_index(), 
      GetArena());
  }
  c_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_c().empty()) {
    c_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_c(), 
      GetArena());
  }
  if (from._internal_has_psi()) {
    psi_ = new ::safeheron::proto::PailBlumModulusProof(*from.psi_);
  } else {
    psi_ = nullptr;
  }
  if (from._internal_has_phi_ij()) {
    phi_ij_ = new ::safeheron::proto::NoSmallFactorProof(*from.phi_ij_);
  } else {
    phi_ij_ = nullptr;
  }
  if (from._internal_has_pi()) {
    pi_ = new ::safeheron::proto::DLogProof_V2(*from.pi_);
  } else {
    pi_ = nullptr;
  }
  if (from._internal_has_psi_ij()) {
    psi_ij_ = new ::safeheron::proto::DLogProof_V2(*from.psi_ij_);
  } else {
    psi_ij_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
}

void Round2P2PMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  ssid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  c_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&psi_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&psi_ij_) -
      reinterpret_cast<char*>(&psi_)) + sizeof(psi_ij_));
}

Round2P2PMessage::~Round2P2PMessage() {
  // @@protoc_insertion_point(destructor:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Round2P2PMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ssid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  index_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  c_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete psi_;
  if (this != internal_default_instance()) delete phi_ij_;
  if (this != internal_default_instance()) delete pi_;
  if (this != internal_default_instance()) delete psi_ij_;
}

void Round2P2PMessage::ArenaDtor(void* object) {
  Round2P2PMessage* _this = reinterpret_cast< Round2P2PMessage* >(object);
  (void)_this;
}
void Round2P2PMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Round2P2PMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Round2P2PMessage& Round2P2PMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Round2P2PMessage_cmp_2faux_5finfo_5fkey_5frefresh_2eproto.base);
  return *internal_default_instance();
}


void Round2P2PMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ssid_.ClearToEmpty();
  index_.ClearToEmpty();
  c_.ClearToEmpty();
  if (GetArena() == nullptr && psi_ != nullptr) {
    delete psi_;
  }
  psi_ = nullptr;
  if (GetArena() == nullptr && phi_ij_ != nullptr) {
    delete phi_ij_;
  }
  phi_ij_ = nullptr;
  if (GetArena() == nullptr && pi_ != nullptr) {
    delete pi_;
  }
  pi_ = nullptr;
  if (GetArena() == nullptr && psi_ij_ != nullptr) {
    delete psi_ij_;
  }
  psi_ij_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Round2P2PMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string ssid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ssid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.ssid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_index();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.index"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.PailBlumModulusProof psi = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_psi(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.NoSmallFactorProof phi_ij = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_phi_ij(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.DLogProof_V2 pi = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_pi(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string C = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_c();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.C"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .safeheron.proto.DLogProof_V2 psi_ij = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_psi_ij(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Round2P2PMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ssid().data(), static_cast<int>(this->_internal_ssid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.ssid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ssid(), target);
  }

  // string index = 2;
  if (this->index().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_index().data(), static_cast<int>(this->_internal_index().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.index");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_index(), target);
  }

  // .safeheron.proto.PailBlumModulusProof psi = 3;
  if (this->has_psi()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::psi(this), target, stream);
  }

  // .safeheron.proto.NoSmallFactorProof phi_ij = 4;
  if (this->has_phi_ij()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::phi_ij(this), target, stream);
  }

  // .safeheron.proto.DLogProof_V2 pi = 5;
  if (this->has_pi()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::pi(this), target, stream);
  }

  // string C = 6;
  if (this->c().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_c().data(), static_cast<int>(this->_internal_c().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage.C");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_c(), target);
  }

  // .safeheron.proto.DLogProof_V2 psi_ij = 7;
  if (this->has_psi_ij()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::psi_ij(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  return target;
}

size_t Round2P2PMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ssid = 1;
  if (this->ssid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());
  }

  // string index = 2;
  if (this->index().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_index());
  }

  // string C = 6;
  if (this->c().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_c());
  }

  // .safeheron.proto.PailBlumModulusProof psi = 3;
  if (this->has_psi()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *psi_);
  }

  // .safeheron.proto.NoSmallFactorProof phi_ij = 4;
  if (this->has_phi_ij()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *phi_ij_);
  }

  // .safeheron.proto.DLogProof_V2 pi = 5;
  if (this->has_pi()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *pi_);
  }

  // .safeheron.proto.DLogProof_V2 psi_ij = 7;
  if (this->has_psi_ij()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *psi_ij_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Round2P2PMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const Round2P2PMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Round2P2PMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
    MergeFrom(*source);
  }
}

void Round2P2PMessage::MergeFrom(const Round2P2PMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ssid().size() > 0) {
    _internal_set_ssid(from._internal_ssid());
  }
  if (from.index().size() > 0) {
    _internal_set_index(from._internal_index());
  }
  if (from.c().size() > 0) {
    _internal_set_c(from._internal_c());
  }
  if (from.has_psi()) {
    _internal_mutable_psi()->::safeheron::proto::PailBlumModulusProof::MergeFrom(from._internal_psi());
  }
  if (from.has_phi_ij()) {
    _internal_mutable_phi_ij()->::safeheron::proto::NoSmallFactorProof::MergeFrom(from._internal_phi_ij());
  }
  if (from.has_pi()) {
    _internal_mutable_pi()->::safeheron::proto::DLogProof_V2::MergeFrom(from._internal_pi());
  }
  if (from.has_psi_ij()) {
    _internal_mutable_psi_ij()->::safeheron::proto::DLogProof_V2::MergeFrom(from._internal_psi_ij());
  }
}

void Round2P2PMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Round2P2PMessage::CopyFrom(const Round2P2PMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.multi_party_ecdsa.cmp.aux_info_key_refresh.Round2P2PMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Round2P2PMessage::IsInitialized() const {
  return true;
}

void Round2P2PMessage::InternalSwap(Round2P2PMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ssid_.Swap(&other->ssid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  index_.Swap(&other->index_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  c_.Swap(&other->c_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Round2P2PMessage, psi_ij_)
      + sizeof(Round2P2PMessage::psi_ij_)
      - PROTOBUF_FIELD_OFFSET(Round2P2PMessage, psi_)>(
          reinterpret_cast<char*>(&psi_),
          reinterpret_cast<char*>(&other->psi_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Round2P2PMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace aux_info_key_refresh
}  // namespace cmp
}  // namespace multi_party_ecdsa
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage* Arena::CreateMaybeMessage< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round0BCMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage* Arena::CreateMaybeMessage< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round1BCMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage* Arena::CreateMaybeMessage< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::multi_party_ecdsa::cmp::aux_info_key_refresh::Round2P2PMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
