// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lindell17/sign.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lindell17_2fsign_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lindell17_2fsign_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-suites/crypto-curve/proto_gen/curve_point.pb.switch.h"
#include "crypto-suites/crypto-zkp/proto_gen/zkp.pb.switch.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lindell17_2fsign_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lindell17_2fsign_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lindell17_2fsign_2eproto;
namespace safeheron {
namespace proto {
namespace two_party_ecdsa {
namespace lindell17 {
namespace sign {
class P1Message0;
class P1Message0DefaultTypeInternal;
extern P1Message0DefaultTypeInternal _P1Message0_default_instance_;
class P1Message1;
class P1Message1DefaultTypeInternal;
extern P1Message1DefaultTypeInternal _P1Message1_default_instance_;
class P1Message2;
class P1Message2DefaultTypeInternal;
extern P1Message2DefaultTypeInternal _P1Message2_default_instance_;
class P2Message0;
class P2Message0DefaultTypeInternal;
extern P2Message0DefaultTypeInternal _P2Message0_default_instance_;
class P2Message1;
class P2Message1DefaultTypeInternal;
extern P2Message1DefaultTypeInternal _P2Message1_default_instance_;
class P2Message2;
class P2Message2DefaultTypeInternal;
extern P2Message2DefaultTypeInternal _P2Message2_default_instance_;
}  // namespace sign
}  // namespace lindell17
}  // namespace two_party_ecdsa
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message0* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message0>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message1* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message1>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message2* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P1Message2>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message0* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message0>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message1* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message1>(Arena*);
template<> ::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message2* Arena::CreateMaybeMessage<::safeheron::proto::two_party_ecdsa::lindell17::sign::P2Message2>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {
namespace two_party_ecdsa {
namespace lindell17 {
namespace sign {

// ===================================================================

class P1Message0 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0) */ {
 public:
  inline P1Message0() : P1Message0(nullptr) {}
  virtual ~P1Message0();

  P1Message0(const P1Message0& from);
  P1Message0(P1Message0&& from) noexcept
    : P1Message0() {
    *this = ::std::move(from);
  }

  inline P1Message0& operator=(const P1Message0& from) {
    CopyFrom(from);
    return *this;
  }
  inline P1Message0& operator=(P1Message0&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P1Message0& default_instance();

  static inline const P1Message0* internal_default_instance() {
    return reinterpret_cast<const P1Message0*>(
               &_P1Message0_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(P1Message0& a, P1Message0& b) {
    a.Swap(&b);
  }
  inline void Swap(P1Message0* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P1Message0* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P1Message0* New() const final {
    return CreateMaybeMessage<P1Message0>(nullptr);
  }

  P1Message0* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P1Message0>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P1Message0& from);
  void MergeFrom(const P1Message0& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P1Message0* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0";
  }
  protected:
  explicit P1Message0(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSid1CommitmentFieldNumber = 1,
  };
  // string sid1_commitment = 1;
  void clear_sid1_commitment();
  const std::string& sid1_commitment() const;
  void set_sid1_commitment(const std::string& value);
  void set_sid1_commitment(std::string&& value);
  void set_sid1_commitment(const char* value);
  void set_sid1_commitment(const char* value, size_t size);
  std::string* mutable_sid1_commitment();
  std::string* release_sid1_commitment();
  void set_allocated_sid1_commitment(std::string* sid1_commitment);
  private:
  const std::string& _internal_sid1_commitment() const;
  void _internal_set_sid1_commitment(const std::string& value);
  std::string* _internal_mutable_sid1_commitment();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sid1_commitment_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// -------------------------------------------------------------------

class P2Message0 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0) */ {
 public:
  inline P2Message0() : P2Message0(nullptr) {}
  virtual ~P2Message0();

  P2Message0(const P2Message0& from);
  P2Message0(P2Message0&& from) noexcept
    : P2Message0() {
    *this = ::std::move(from);
  }

  inline P2Message0& operator=(const P2Message0& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2Message0& operator=(P2Message0&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P2Message0& default_instance();

  static inline const P2Message0* internal_default_instance() {
    return reinterpret_cast<const P2Message0*>(
               &_P2Message0_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(P2Message0& a, P2Message0& b) {
    a.Swap(&b);
  }
  inline void Swap(P2Message0* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2Message0* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2Message0* New() const final {
    return CreateMaybeMessage<P2Message0>(nullptr);
  }

  P2Message0* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2Message0>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2Message0& from);
  void MergeFrom(const P2Message0& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2Message0* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0";
  }
  protected:
  explicit P2Message0(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSid2FieldNumber = 1,
  };
  // string sid2 = 1;
  void clear_sid2();
  const std::string& sid2() const;
  void set_sid2(const std::string& value);
  void set_sid2(std::string&& value);
  void set_sid2(const char* value);
  void set_sid2(const char* value, size_t size);
  std::string* mutable_sid2();
  std::string* release_sid2();
  void set_allocated_sid2(std::string* sid2);
  private:
  const std::string& _internal_sid2() const;
  void _internal_set_sid2(const std::string& value);
  std::string* _internal_mutable_sid2();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sid2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// -------------------------------------------------------------------

class P1Message1 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1) */ {
 public:
  inline P1Message1() : P1Message1(nullptr) {}
  virtual ~P1Message1();

  P1Message1(const P1Message1& from);
  P1Message1(P1Message1&& from) noexcept
    : P1Message1() {
    *this = ::std::move(from);
  }

  inline P1Message1& operator=(const P1Message1& from) {
    CopyFrom(from);
    return *this;
  }
  inline P1Message1& operator=(P1Message1&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P1Message1& default_instance();

  static inline const P1Message1* internal_default_instance() {
    return reinterpret_cast<const P1Message1*>(
               &_P1Message1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(P1Message1& a, P1Message1& b) {
    a.Swap(&b);
  }
  inline void Swap(P1Message1* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P1Message1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P1Message1* New() const final {
    return CreateMaybeMessage<P1Message1>(nullptr);
  }

  P1Message1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P1Message1>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P1Message1& from);
  void MergeFrom(const P1Message1& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P1Message1* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1";
  }
  protected:
  explicit P1Message1(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSid1FieldNumber = 1,
    kSid1BlindFactorFieldNumber = 2,
    kZkPkCommitmentFieldNumber = 3,
  };
  // string sid1 = 1;
  void clear_sid1();
  const std::string& sid1() const;
  void set_sid1(const std::string& value);
  void set_sid1(std::string&& value);
  void set_sid1(const char* value);
  void set_sid1(const char* value, size_t size);
  std::string* mutable_sid1();
  std::string* release_sid1();
  void set_allocated_sid1(std::string* sid1);
  private:
  const std::string& _internal_sid1() const;
  void _internal_set_sid1(const std::string& value);
  std::string* _internal_mutable_sid1();
  public:

  // string sid1_blind_factor = 2;
  void clear_sid1_blind_factor();
  const std::string& sid1_blind_factor() const;
  void set_sid1_blind_factor(const std::string& value);
  void set_sid1_blind_factor(std::string&& value);
  void set_sid1_blind_factor(const char* value);
  void set_sid1_blind_factor(const char* value, size_t size);
  std::string* mutable_sid1_blind_factor();
  std::string* release_sid1_blind_factor();
  void set_allocated_sid1_blind_factor(std::string* sid1_blind_factor);
  private:
  const std::string& _internal_sid1_blind_factor() const;
  void _internal_set_sid1_blind_factor(const std::string& value);
  std::string* _internal_mutable_sid1_blind_factor();
  public:

  // string zk_pk_commitment = 3;
  void clear_zk_pk_commitment();
  const std::string& zk_pk_commitment() const;
  void set_zk_pk_commitment(const std::string& value);
  void set_zk_pk_commitment(std::string&& value);
  void set_zk_pk_commitment(const char* value);
  void set_zk_pk_commitment(const char* value, size_t size);
  std::string* mutable_zk_pk_commitment();
  std::string* release_zk_pk_commitment();
  void set_allocated_zk_pk_commitment(std::string* zk_pk_commitment);
  private:
  const std::string& _internal_zk_pk_commitment() const;
  void _internal_set_zk_pk_commitment(const std::string& value);
  std::string* _internal_mutable_zk_pk_commitment();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sid1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sid1_blind_factor_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zk_pk_commitment_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// -------------------------------------------------------------------

class P2Message1 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1) */ {
 public:
  inline P2Message1() : P2Message1(nullptr) {}
  virtual ~P2Message1();

  P2Message1(const P2Message1& from);
  P2Message1(P2Message1&& from) noexcept
    : P2Message1() {
    *this = ::std::move(from);
  }

  inline P2Message1& operator=(const P2Message1& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2Message1& operator=(P2Message1&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P2Message1& default_instance();

  static inline const P2Message1* internal_default_instance() {
    return reinterpret_cast<const P2Message1*>(
               &_P2Message1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(P2Message1& a, P2Message1& b) {
    a.Swap(&b);
  }
  inline void Swap(P2Message1* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2Message1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2Message1* New() const final {
    return CreateMaybeMessage<P2Message1>(nullptr);
  }

  P2Message1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2Message1>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2Message1& from);
  void MergeFrom(const P2Message1& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2Message1* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1";
  }
  protected:
  explicit P2Message1(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kR2FieldNumber = 1,
    kDLogProofR2FieldNumber = 2,
  };
  // .safeheron.proto.CurvePoint R2 = 1;
  bool has_r2() const;
  private:
  bool _internal_has_r2() const;
  public:
  void clear_r2();
  const ::safeheron::proto::CurvePoint& r2() const;
  ::safeheron::proto::CurvePoint* release_r2();
  ::safeheron::proto::CurvePoint* mutable_r2();
  void set_allocated_r2(::safeheron::proto::CurvePoint* r2);
  private:
  const ::safeheron::proto::CurvePoint& _internal_r2() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_r2();
  public:
  void unsafe_arena_set_allocated_r2(
      ::safeheron::proto::CurvePoint* r2);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_r2();

  // .safeheron.proto.DLogProof_V2 d_log_proof_R2 = 2;
  bool has_d_log_proof_r2() const;
  private:
  bool _internal_has_d_log_proof_r2() const;
  public:
  void clear_d_log_proof_r2();
  const ::safeheron::proto::DLogProof_V2& d_log_proof_r2() const;
  ::safeheron::proto::DLogProof_V2* release_d_log_proof_r2();
  ::safeheron::proto::DLogProof_V2* mutable_d_log_proof_r2();
  void set_allocated_d_log_proof_r2(::safeheron::proto::DLogProof_V2* d_log_proof_r2);
  private:
  const ::safeheron::proto::DLogProof_V2& _internal_d_log_proof_r2() const;
  ::safeheron::proto::DLogProof_V2* _internal_mutable_d_log_proof_r2();
  public:
  void unsafe_arena_set_allocated_d_log_proof_r2(
      ::safeheron::proto::DLogProof_V2* d_log_proof_r2);
  ::safeheron::proto::DLogProof_V2* unsafe_arena_release_d_log_proof_r2();

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::safeheron::proto::CurvePoint* r2_;
  ::safeheron::proto::DLogProof_V2* d_log_proof_r2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// -------------------------------------------------------------------

class P1Message2 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2) */ {
 public:
  inline P1Message2() : P1Message2(nullptr) {}
  virtual ~P1Message2();

  P1Message2(const P1Message2& from);
  P1Message2(P1Message2&& from) noexcept
    : P1Message2() {
    *this = ::std::move(from);
  }

  inline P1Message2& operator=(const P1Message2& from) {
    CopyFrom(from);
    return *this;
  }
  inline P1Message2& operator=(P1Message2&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P1Message2& default_instance();

  static inline const P1Message2* internal_default_instance() {
    return reinterpret_cast<const P1Message2*>(
               &_P1Message2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(P1Message2& a, P1Message2& b) {
    a.Swap(&b);
  }
  inline void Swap(P1Message2* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P1Message2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P1Message2* New() const final {
    return CreateMaybeMessage<P1Message2>(nullptr);
  }

  P1Message2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P1Message2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P1Message2& from);
  void MergeFrom(const P1Message2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P1Message2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2";
  }
  protected:
  explicit P1Message2(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTFieldNumber = 3,
    kZkPkBlindFactorFieldNumber = 4,
    kR1FieldNumber = 1,
    kDLogProofR1FieldNumber = 2,
  };
  // string t = 3;
  void clear_t();
  const std::string& t() const;
  void set_t(const std::string& value);
  void set_t(std::string&& value);
  void set_t(const char* value);
  void set_t(const char* value, size_t size);
  std::string* mutable_t();
  std::string* release_t();
  void set_allocated_t(std::string* t);
  private:
  const std::string& _internal_t() const;
  void _internal_set_t(const std::string& value);
  std::string* _internal_mutable_t();
  public:

  // string zk_pk_blind_factor = 4;
  void clear_zk_pk_blind_factor();
  const std::string& zk_pk_blind_factor() const;
  void set_zk_pk_blind_factor(const std::string& value);
  void set_zk_pk_blind_factor(std::string&& value);
  void set_zk_pk_blind_factor(const char* value);
  void set_zk_pk_blind_factor(const char* value, size_t size);
  std::string* mutable_zk_pk_blind_factor();
  std::string* release_zk_pk_blind_factor();
  void set_allocated_zk_pk_blind_factor(std::string* zk_pk_blind_factor);
  private:
  const std::string& _internal_zk_pk_blind_factor() const;
  void _internal_set_zk_pk_blind_factor(const std::string& value);
  std::string* _internal_mutable_zk_pk_blind_factor();
  public:

  // .safeheron.proto.CurvePoint R1 = 1;
  bool has_r1() const;
  private:
  bool _internal_has_r1() const;
  public:
  void clear_r1();
  const ::safeheron::proto::CurvePoint& r1() const;
  ::safeheron::proto::CurvePoint* release_r1();
  ::safeheron::proto::CurvePoint* mutable_r1();
  void set_allocated_r1(::safeheron::proto::CurvePoint* r1);
  private:
  const ::safeheron::proto::CurvePoint& _internal_r1() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_r1();
  public:
  void unsafe_arena_set_allocated_r1(
      ::safeheron::proto::CurvePoint* r1);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_r1();

  // .safeheron.proto.DLogProof_V2 d_log_proof_R1 = 2;
  bool has_d_log_proof_r1() const;
  private:
  bool _internal_has_d_log_proof_r1() const;
  public:
  void clear_d_log_proof_r1();
  const ::safeheron::proto::DLogProof_V2& d_log_proof_r1() const;
  ::safeheron::proto::DLogProof_V2* release_d_log_proof_r1();
  ::safeheron::proto::DLogProof_V2* mutable_d_log_proof_r1();
  void set_allocated_d_log_proof_r1(::safeheron::proto::DLogProof_V2* d_log_proof_r1);
  private:
  const ::safeheron::proto::DLogProof_V2& _internal_d_log_proof_r1() const;
  ::safeheron::proto::DLogProof_V2* _internal_mutable_d_log_proof_r1();
  public:
  void unsafe_arena_set_allocated_d_log_proof_r1(
      ::safeheron::proto::DLogProof_V2* d_log_proof_r1);
  ::safeheron::proto::DLogProof_V2* unsafe_arena_release_d_log_proof_r1();

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr t_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zk_pk_blind_factor_;
  ::safeheron::proto::CurvePoint* r1_;
  ::safeheron::proto::DLogProof_V2* d_log_proof_r1_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// -------------------------------------------------------------------

class P2Message2 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2) */ {
 public:
  inline P2Message2() : P2Message2(nullptr) {}
  virtual ~P2Message2();

  P2Message2(const P2Message2& from);
  P2Message2(P2Message2&& from) noexcept
    : P2Message2() {
    *this = ::std::move(from);
  }

  inline P2Message2& operator=(const P2Message2& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2Message2& operator=(P2Message2&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const P2Message2& default_instance();

  static inline const P2Message2* internal_default_instance() {
    return reinterpret_cast<const P2Message2*>(
               &_P2Message2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(P2Message2& a, P2Message2& b) {
    a.Swap(&b);
  }
  inline void Swap(P2Message2* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2Message2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2Message2* New() const final {
    return CreateMaybeMessage<P2Message2>(nullptr);
  }

  P2Message2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2Message2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2Message2& from);
  void MergeFrom(const P2Message2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2Message2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2";
  }
  protected:
  explicit P2Message2(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lindell17_2fsign_2eproto);
    return ::descriptor_table_lindell17_2fsign_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kC3FieldNumber = 1,
  };
  // string c3 = 1;
  void clear_c3();
  const std::string& c3() const;
  void set_c3(const std::string& value);
  void set_c3(std::string&& value);
  void set_c3(const char* value);
  void set_c3(const char* value, size_t size);
  std::string* mutable_c3();
  std::string* release_c3();
  void set_allocated_c3(std::string* c3);
  private:
  const std::string& _internal_c3() const;
  void _internal_set_c3(const std::string& value);
  std::string* _internal_mutable_c3();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr c3_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lindell17_2fsign_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// P1Message0

// string sid1_commitment = 1;
inline void P1Message0::clear_sid1_commitment() {
  sid1_commitment_.ClearToEmpty();
}
inline const std::string& P1Message0::sid1_commitment() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
  return _internal_sid1_commitment();
}
inline void P1Message0::set_sid1_commitment(const std::string& value) {
  _internal_set_sid1_commitment(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
}
inline std::string* P1Message0::mutable_sid1_commitment() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
  return _internal_mutable_sid1_commitment();
}
inline const std::string& P1Message0::_internal_sid1_commitment() const {
  return sid1_commitment_.Get();
}
inline void P1Message0::_internal_set_sid1_commitment(const std::string& value) {
  
  sid1_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message0::set_sid1_commitment(std::string&& value) {
  
  sid1_commitment_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
}
inline void P1Message0::set_sid1_commitment(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sid1_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
}
inline void P1Message0::set_sid1_commitment(const char* value,
    size_t size) {
  
  sid1_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
}
inline std::string* P1Message0::_internal_mutable_sid1_commitment() {
  
  return sid1_commitment_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message0::release_sid1_commitment() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
  return sid1_commitment_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message0::set_allocated_sid1_commitment(std::string* sid1_commitment) {
  if (sid1_commitment != nullptr) {
    
  } else {
    
  }
  sid1_commitment_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sid1_commitment,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message0.sid1_commitment)
}

// -------------------------------------------------------------------

// P2Message0

// string sid2 = 1;
inline void P2Message0::clear_sid2() {
  sid2_.ClearToEmpty();
}
inline const std::string& P2Message0::sid2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
  return _internal_sid2();
}
inline void P2Message0::set_sid2(const std::string& value) {
  _internal_set_sid2(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
}
inline std::string* P2Message0::mutable_sid2() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
  return _internal_mutable_sid2();
}
inline const std::string& P2Message0::_internal_sid2() const {
  return sid2_.Get();
}
inline void P2Message0::_internal_set_sid2(const std::string& value) {
  
  sid2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P2Message0::set_sid2(std::string&& value) {
  
  sid2_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
}
inline void P2Message0::set_sid2(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sid2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
}
inline void P2Message0::set_sid2(const char* value,
    size_t size) {
  
  sid2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
}
inline std::string* P2Message0::_internal_mutable_sid2() {
  
  return sid2_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P2Message0::release_sid2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
  return sid2_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P2Message0::set_allocated_sid2(std::string* sid2) {
  if (sid2 != nullptr) {
    
  } else {
    
  }
  sid2_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sid2,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message0.sid2)
}

// -------------------------------------------------------------------

// P1Message1

// string sid1 = 1;
inline void P1Message1::clear_sid1() {
  sid1_.ClearToEmpty();
}
inline const std::string& P1Message1::sid1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
  return _internal_sid1();
}
inline void P1Message1::set_sid1(const std::string& value) {
  _internal_set_sid1(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
}
inline std::string* P1Message1::mutable_sid1() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
  return _internal_mutable_sid1();
}
inline const std::string& P1Message1::_internal_sid1() const {
  return sid1_.Get();
}
inline void P1Message1::_internal_set_sid1(const std::string& value) {
  
  sid1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message1::set_sid1(std::string&& value) {
  
  sid1_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
}
inline void P1Message1::set_sid1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sid1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
}
inline void P1Message1::set_sid1(const char* value,
    size_t size) {
  
  sid1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
}
inline std::string* P1Message1::_internal_mutable_sid1() {
  
  return sid1_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message1::release_sid1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
  return sid1_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message1::set_allocated_sid1(std::string* sid1) {
  if (sid1 != nullptr) {
    
  } else {
    
  }
  sid1_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sid1,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1)
}

// string sid1_blind_factor = 2;
inline void P1Message1::clear_sid1_blind_factor() {
  sid1_blind_factor_.ClearToEmpty();
}
inline const std::string& P1Message1::sid1_blind_factor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
  return _internal_sid1_blind_factor();
}
inline void P1Message1::set_sid1_blind_factor(const std::string& value) {
  _internal_set_sid1_blind_factor(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
}
inline std::string* P1Message1::mutable_sid1_blind_factor() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
  return _internal_mutable_sid1_blind_factor();
}
inline const std::string& P1Message1::_internal_sid1_blind_factor() const {
  return sid1_blind_factor_.Get();
}
inline void P1Message1::_internal_set_sid1_blind_factor(const std::string& value) {
  
  sid1_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message1::set_sid1_blind_factor(std::string&& value) {
  
  sid1_blind_factor_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
}
inline void P1Message1::set_sid1_blind_factor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sid1_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
}
inline void P1Message1::set_sid1_blind_factor(const char* value,
    size_t size) {
  
  sid1_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
}
inline std::string* P1Message1::_internal_mutable_sid1_blind_factor() {
  
  return sid1_blind_factor_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message1::release_sid1_blind_factor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
  return sid1_blind_factor_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message1::set_allocated_sid1_blind_factor(std::string* sid1_blind_factor) {
  if (sid1_blind_factor != nullptr) {
    
  } else {
    
  }
  sid1_blind_factor_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sid1_blind_factor,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.sid1_blind_factor)
}

// string zk_pk_commitment = 3;
inline void P1Message1::clear_zk_pk_commitment() {
  zk_pk_commitment_.ClearToEmpty();
}
inline const std::string& P1Message1::zk_pk_commitment() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
  return _internal_zk_pk_commitment();
}
inline void P1Message1::set_zk_pk_commitment(const std::string& value) {
  _internal_set_zk_pk_commitment(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
}
inline std::string* P1Message1::mutable_zk_pk_commitment() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
  return _internal_mutable_zk_pk_commitment();
}
inline const std::string& P1Message1::_internal_zk_pk_commitment() const {
  return zk_pk_commitment_.Get();
}
inline void P1Message1::_internal_set_zk_pk_commitment(const std::string& value) {
  
  zk_pk_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message1::set_zk_pk_commitment(std::string&& value) {
  
  zk_pk_commitment_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
}
inline void P1Message1::set_zk_pk_commitment(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  zk_pk_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
}
inline void P1Message1::set_zk_pk_commitment(const char* value,
    size_t size) {
  
  zk_pk_commitment_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
}
inline std::string* P1Message1::_internal_mutable_zk_pk_commitment() {
  
  return zk_pk_commitment_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message1::release_zk_pk_commitment() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
  return zk_pk_commitment_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message1::set_allocated_zk_pk_commitment(std::string* zk_pk_commitment) {
  if (zk_pk_commitment != nullptr) {
    
  } else {
    
  }
  zk_pk_commitment_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), zk_pk_commitment,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message1.zk_pk_commitment)
}

// -------------------------------------------------------------------

// P2Message1

// .safeheron.proto.CurvePoint R2 = 1;
inline bool P2Message1::_internal_has_r2() const {
  return this != internal_default_instance() && r2_ != nullptr;
}
inline bool P2Message1::has_r2() const {
  return _internal_has_r2();
}
inline const ::safeheron::proto::CurvePoint& P2Message1::_internal_r2() const {
  const ::safeheron::proto::CurvePoint* p = r2_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& P2Message1::r2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.R2)
  return _internal_r2();
}
inline void P2Message1::unsafe_arena_set_allocated_r2(
    ::safeheron::proto::CurvePoint* r2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(r2_);
  }
  r2_ = r2;
  if (r2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.R2)
}
inline ::safeheron::proto::CurvePoint* P2Message1::release_r2() {
  
  ::safeheron::proto::CurvePoint* temp = r2_;
  r2_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::CurvePoint* P2Message1::unsafe_arena_release_r2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.R2)
  
  ::safeheron::proto::CurvePoint* temp = r2_;
  r2_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* P2Message1::_internal_mutable_r2() {
  
  if (r2_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArena());
    r2_ = p;
  }
  return r2_;
}
inline ::safeheron::proto::CurvePoint* P2Message1::mutable_r2() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.R2)
  return _internal_mutable_r2();
}
inline void P2Message1::set_allocated_r2(::safeheron::proto::CurvePoint* r2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(r2_);
  }
  if (r2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(r2)->GetArena();
    if (message_arena != submessage_arena) {
      r2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, r2, submessage_arena);
    }
    
  } else {
    
  }
  r2_ = r2;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.R2)
}

// .safeheron.proto.DLogProof_V2 d_log_proof_R2 = 2;
inline bool P2Message1::_internal_has_d_log_proof_r2() const {
  return this != internal_default_instance() && d_log_proof_r2_ != nullptr;
}
inline bool P2Message1::has_d_log_proof_r2() const {
  return _internal_has_d_log_proof_r2();
}
inline const ::safeheron::proto::DLogProof_V2& P2Message1::_internal_d_log_proof_r2() const {
  const ::safeheron::proto::DLogProof_V2* p = d_log_proof_r2_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::DLogProof_V2&>(
      ::safeheron::proto::_DLogProof_V2_default_instance_);
}
inline const ::safeheron::proto::DLogProof_V2& P2Message1::d_log_proof_r2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.d_log_proof_R2)
  return _internal_d_log_proof_r2();
}
inline void P2Message1::unsafe_arena_set_allocated_d_log_proof_r2(
    ::safeheron::proto::DLogProof_V2* d_log_proof_r2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r2_);
  }
  d_log_proof_r2_ = d_log_proof_r2;
  if (d_log_proof_r2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.d_log_proof_R2)
}
inline ::safeheron::proto::DLogProof_V2* P2Message1::release_d_log_proof_r2() {
  
  ::safeheron::proto::DLogProof_V2* temp = d_log_proof_r2_;
  d_log_proof_r2_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::DLogProof_V2* P2Message1::unsafe_arena_release_d_log_proof_r2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.d_log_proof_R2)
  
  ::safeheron::proto::DLogProof_V2* temp = d_log_proof_r2_;
  d_log_proof_r2_ = nullptr;
  return temp;
}
inline ::safeheron::proto::DLogProof_V2* P2Message1::_internal_mutable_d_log_proof_r2() {
  
  if (d_log_proof_r2_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::DLogProof_V2>(GetArena());
    d_log_proof_r2_ = p;
  }
  return d_log_proof_r2_;
}
inline ::safeheron::proto::DLogProof_V2* P2Message1::mutable_d_log_proof_r2() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.d_log_proof_R2)
  return _internal_mutable_d_log_proof_r2();
}
inline void P2Message1::set_allocated_d_log_proof_r2(::safeheron::proto::DLogProof_V2* d_log_proof_r2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r2_);
  }
  if (d_log_proof_r2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r2)->GetArena();
    if (message_arena != submessage_arena) {
      d_log_proof_r2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, d_log_proof_r2, submessage_arena);
    }
    
  } else {
    
  }
  d_log_proof_r2_ = d_log_proof_r2;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message1.d_log_proof_R2)
}

// -------------------------------------------------------------------

// P1Message2

// .safeheron.proto.CurvePoint R1 = 1;
inline bool P1Message2::_internal_has_r1() const {
  return this != internal_default_instance() && r1_ != nullptr;
}
inline bool P1Message2::has_r1() const {
  return _internal_has_r1();
}
inline const ::safeheron::proto::CurvePoint& P1Message2::_internal_r1() const {
  const ::safeheron::proto::CurvePoint* p = r1_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& P1Message2::r1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.R1)
  return _internal_r1();
}
inline void P1Message2::unsafe_arena_set_allocated_r1(
    ::safeheron::proto::CurvePoint* r1) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(r1_);
  }
  r1_ = r1;
  if (r1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.R1)
}
inline ::safeheron::proto::CurvePoint* P1Message2::release_r1() {
  
  ::safeheron::proto::CurvePoint* temp = r1_;
  r1_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::CurvePoint* P1Message2::unsafe_arena_release_r1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.R1)
  
  ::safeheron::proto::CurvePoint* temp = r1_;
  r1_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* P1Message2::_internal_mutable_r1() {
  
  if (r1_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArena());
    r1_ = p;
  }
  return r1_;
}
inline ::safeheron::proto::CurvePoint* P1Message2::mutable_r1() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.R1)
  return _internal_mutable_r1();
}
inline void P1Message2::set_allocated_r1(::safeheron::proto::CurvePoint* r1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(r1_);
  }
  if (r1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(r1)->GetArena();
    if (message_arena != submessage_arena) {
      r1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, r1, submessage_arena);
    }
    
  } else {
    
  }
  r1_ = r1;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.R1)
}

// .safeheron.proto.DLogProof_V2 d_log_proof_R1 = 2;
inline bool P1Message2::_internal_has_d_log_proof_r1() const {
  return this != internal_default_instance() && d_log_proof_r1_ != nullptr;
}
inline bool P1Message2::has_d_log_proof_r1() const {
  return _internal_has_d_log_proof_r1();
}
inline const ::safeheron::proto::DLogProof_V2& P1Message2::_internal_d_log_proof_r1() const {
  const ::safeheron::proto::DLogProof_V2* p = d_log_proof_r1_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::DLogProof_V2&>(
      ::safeheron::proto::_DLogProof_V2_default_instance_);
}
inline const ::safeheron::proto::DLogProof_V2& P1Message2::d_log_proof_r1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.d_log_proof_R1)
  return _internal_d_log_proof_r1();
}
inline void P1Message2::unsafe_arena_set_allocated_d_log_proof_r1(
    ::safeheron::proto::DLogProof_V2* d_log_proof_r1) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r1_);
  }
  d_log_proof_r1_ = d_log_proof_r1;
  if (d_log_proof_r1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.d_log_proof_R1)
}
inline ::safeheron::proto::DLogProof_V2* P1Message2::release_d_log_proof_r1() {
  
  ::safeheron::proto::DLogProof_V2* temp = d_log_proof_r1_;
  d_log_proof_r1_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::DLogProof_V2* P1Message2::unsafe_arena_release_d_log_proof_r1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.d_log_proof_R1)
  
  ::safeheron::proto::DLogProof_V2* temp = d_log_proof_r1_;
  d_log_proof_r1_ = nullptr;
  return temp;
}
inline ::safeheron::proto::DLogProof_V2* P1Message2::_internal_mutable_d_log_proof_r1() {
  
  if (d_log_proof_r1_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::DLogProof_V2>(GetArena());
    d_log_proof_r1_ = p;
  }
  return d_log_proof_r1_;
}
inline ::safeheron::proto::DLogProof_V2* P1Message2::mutable_d_log_proof_r1() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.d_log_proof_R1)
  return _internal_mutable_d_log_proof_r1();
}
inline void P1Message2::set_allocated_d_log_proof_r1(::safeheron::proto::DLogProof_V2* d_log_proof_r1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r1_);
  }
  if (d_log_proof_r1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_log_proof_r1)->GetArena();
    if (message_arena != submessage_arena) {
      d_log_proof_r1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, d_log_proof_r1, submessage_arena);
    }
    
  } else {
    
  }
  d_log_proof_r1_ = d_log_proof_r1;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.d_log_proof_R1)
}

// string t = 3;
inline void P1Message2::clear_t() {
  t_.ClearToEmpty();
}
inline const std::string& P1Message2::t() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
  return _internal_t();
}
inline void P1Message2::set_t(const std::string& value) {
  _internal_set_t(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
}
inline std::string* P1Message2::mutable_t() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
  return _internal_mutable_t();
}
inline const std::string& P1Message2::_internal_t() const {
  return t_.Get();
}
inline void P1Message2::_internal_set_t(const std::string& value) {
  
  t_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message2::set_t(std::string&& value) {
  
  t_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
}
inline void P1Message2::set_t(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  t_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
}
inline void P1Message2::set_t(const char* value,
    size_t size) {
  
  t_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
}
inline std::string* P1Message2::_internal_mutable_t() {
  
  return t_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message2::release_t() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
  return t_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message2::set_allocated_t(std::string* t) {
  if (t != nullptr) {
    
  } else {
    
  }
  t_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), t,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.t)
}

// string zk_pk_blind_factor = 4;
inline void P1Message2::clear_zk_pk_blind_factor() {
  zk_pk_blind_factor_.ClearToEmpty();
}
inline const std::string& P1Message2::zk_pk_blind_factor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
  return _internal_zk_pk_blind_factor();
}
inline void P1Message2::set_zk_pk_blind_factor(const std::string& value) {
  _internal_set_zk_pk_blind_factor(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
}
inline std::string* P1Message2::mutable_zk_pk_blind_factor() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
  return _internal_mutable_zk_pk_blind_factor();
}
inline const std::string& P1Message2::_internal_zk_pk_blind_factor() const {
  return zk_pk_blind_factor_.Get();
}
inline void P1Message2::_internal_set_zk_pk_blind_factor(const std::string& value) {
  
  zk_pk_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P1Message2::set_zk_pk_blind_factor(std::string&& value) {
  
  zk_pk_blind_factor_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
}
inline void P1Message2::set_zk_pk_blind_factor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  zk_pk_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
}
inline void P1Message2::set_zk_pk_blind_factor(const char* value,
    size_t size) {
  
  zk_pk_blind_factor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
}
inline std::string* P1Message2::_internal_mutable_zk_pk_blind_factor() {
  
  return zk_pk_blind_factor_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P1Message2::release_zk_pk_blind_factor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
  return zk_pk_blind_factor_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P1Message2::set_allocated_zk_pk_blind_factor(std::string* zk_pk_blind_factor) {
  if (zk_pk_blind_factor != nullptr) {
    
  } else {
    
  }
  zk_pk_blind_factor_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), zk_pk_blind_factor,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P1Message2.zk_pk_blind_factor)
}

// -------------------------------------------------------------------

// P2Message2

// string c3 = 1;
inline void P2Message2::clear_c3() {
  c3_.ClearToEmpty();
}
inline const std::string& P2Message2::c3() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
  return _internal_c3();
}
inline void P2Message2::set_c3(const std::string& value) {
  _internal_set_c3(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
}
inline std::string* P2Message2::mutable_c3() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
  return _internal_mutable_c3();
}
inline const std::string& P2Message2::_internal_c3() const {
  return c3_.Get();
}
inline void P2Message2::_internal_set_c3(const std::string& value) {
  
  c3_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void P2Message2::set_c3(std::string&& value) {
  
  c3_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
}
inline void P2Message2::set_c3(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  c3_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
}
inline void P2Message2::set_c3(const char* value,
    size_t size) {
  
  c3_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
}
inline std::string* P2Message2::_internal_mutable_c3() {
  
  return c3_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* P2Message2::release_c3() {
  // @@protoc_insertion_point(field_release:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
  return c3_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void P2Message2::set_allocated_c3(std::string* c3) {
  if (c3 != nullptr) {
    
  } else {
    
  }
  c3_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), c3,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.two_party_ecdsa.lindell17.sign.P2Message2.c3)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sign
}  // namespace lindell17
}  // namespace two_party_ecdsa
}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lindell17_2fsign_2eproto
